create table if not exists members (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table if not exists coupons (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    total_quantity integer not null,
    issued_quantity integer not null,
    issue_start_date timestamp not null,
    issue_end_date timestamp not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table if not exists coupon_issues (
    id bigint generated by default as identity primary key,
    coupon_id bigint not null,
    member_id bigint not null,
    created_at timestamp not null,
    constraint uk_coupon_issue_coupon_member unique (coupon_id, member_id)
);

create index if not exists idx_coupon_issues_coupon_id on coupon_issues (coupon_id);
create index if not exists idx_coupon_issues_member_id on coupon_issues (member_id);
create index if not exists idx_coupon_issues_created_at on coupon_issues (created_at desc);
